kind: Deployment
apiVersion: apps/v1
metadata:
  name: bigcorpapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bigcorpapi
  template:
    metadata:
      labels:
        app: bigcorpapi
    spec:
      containers:
        - name: bigcorpapi
          image: ignaciotwogears/bigcorpapi
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: bigcorpapi-service
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 8000
      protocol: TCP
      nodePort: 31006
  selector:
    app: bigcorpapi