name: Testing and Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        python -m pytest
    - name: login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
    - name: Build
      working-directory: ./Api
      run:  docker build -f dockerfile -t bigcorpapi:latest .
    - name: Tags
      run: |
          docker tag bigcorpapi ${{ secrets.DOCKER_USER }}/bigcorpapi:${{ github.sha }}
          docker tag bigcorpapi ${{ secrets.DOCKER_USER }}/bigcorpapi:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/bigcorpapi:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/bigcorpapi:latest
